=begin
#Siteimprove API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SiteImproveApiClient::A11YSingleIssueHistoryValue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SiteImproveApiClient::A11YSingleIssueHistoryValue do
  let(:instance) { SiteImproveApiClient::A11YSingleIssueHistoryValue.new }

  describe 'test an instance of A11YSingleIssueHistoryValue' do
    it 'should create an instance of A11YSingleIssueHistoryValue' do
      expect(instance).to be_instance_of(SiteImproveApiClient::A11YSingleIssueHistoryValue)
    end
  end
  describe 'test attribute "number_of_pages"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "occurrences"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "timestamp"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
