=begin
#Siteimprove API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SiteimproveAPIClient::Href33
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SiteimproveAPIClient::Href33 do
  let(:instance) { SiteimproveAPIClient::Href33.new }

  describe 'test an instance of Href33' do
    it 'should create an instance of Href33' do
      expect(instance).to be_instance_of(SiteimproveAPIClient::Href33)
    end
  end
  describe 'test attribute "href"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
