=begin
#Siteimprove API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SiteimproveAPIClient::LinksQualityAssuranceReadabilityTestsGunningFog
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SiteimproveAPIClient::LinksQualityAssuranceReadabilityTestsGunningFog do
  let(:instance) { SiteimproveAPIClient::LinksQualityAssuranceReadabilityTestsGunningFog.new }

  describe 'test an instance of LinksQualityAssuranceReadabilityTestsGunningFog' do
    it 'should create an instance of LinksQualityAssuranceReadabilityTestsGunningFog' do
      expect(instance).to be_instance_of(SiteimproveAPIClient::LinksQualityAssuranceReadabilityTestsGunningFog)
    end
  end
  describe 'test attribute "excluded_pages"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "pages"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "scores"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
