=begin
#Siteimprove API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SiteImproveAPIClient::LinksSeov2Overview
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SiteImproveAPIClient::LinksSeov2Overview do
  let(:instance) { SiteImproveAPIClient::LinksSeov2Overview.new }

  describe 'test an instance of LinksSeov2Overview' do
    it 'should create an instance of LinksSeov2Overview' do
      expect(instance).to be_instance_of(SiteImproveAPIClient::LinksSeov2Overview)
    end
  end
  describe 'test attribute "groups"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "score"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
