=begin
#Siteimprove API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SiteImproveApiClient::PageDeletionMetaAnalyticsRelationsCrossProduct
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SiteImproveApiClient::PageDeletionMetaAnalyticsRelationsCrossProduct do
  let(:instance) { SiteImproveApiClient::PageDeletionMetaAnalyticsRelationsCrossProduct.new }

  describe 'test an instance of PageDeletionMetaAnalyticsRelationsCrossProduct' do
    it 'should create an instance of PageDeletionMetaAnalyticsRelationsCrossProduct' do
      expect(instance).to be_instance_of(SiteImproveApiClient::PageDeletionMetaAnalyticsRelationsCrossProduct)
    end
  end
  describe 'test attribute "external_referring_pages"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "has_behaviour_map"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "page_views"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "potential_campaigns"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "potential_key_metrics"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
