=begin
#Siteimprove API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::Links47
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::Links47 do
  let(:instance) { OpenapiClient::Links47.new }

  describe 'test an instance of Links47' do
    it 'should create an instance of Links47' do
      expect(instance).to be_instance_of(OpenapiClient::Links47)
    end
  end
  describe 'test attribute "matches"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
