=begin
#Siteimprove API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::MobileSpeedHistoryItem
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::MobileSpeedHistoryItem do
  let(:instance) { OpenapiClient::MobileSpeedHistoryItem.new }

  describe 'test an instance of MobileSpeedHistoryItem' do
    it 'should create an instance of MobileSpeedHistoryItem' do
      expect(instance).to be_instance_of(OpenapiClient::MobileSpeedHistoryItem)
    end
  end
  describe 'test attribute "speed"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "timestamp"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
