=begin
#Siteimprove API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'date'
require 'time'

module SiteimproveAPIClient
  class PageSizeInfo
    # The complexity of the issue
    attr_accessor :complexity

    # The name of the issue
    attr_accessor :issue_name

    # The type of issue
    attr_accessor :issue_type

    # The number of pages with a size over 1 mb
    attr_accessor :pages_over_1mb

    # The total number of pages
    attr_accessor :total_pages

    attr_accessor :_links

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'complexity' => :'complexity',
        :'issue_name' => :'issue_name',
        :'issue_type' => :'issue_type',
        :'pages_over_1mb' => :'pages_over_1mb',
        :'total_pages' => :'total_pages',
        :'_links' => :'_links'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'complexity' => :'String',
        :'issue_name' => :'String',
        :'issue_type' => :'String',
        :'pages_over_1mb' => :'Integer',
        :'total_pages' => :'Integer',
        :'_links' => :'Links1'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SiteimproveAPIClient::PageSizeInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SiteimproveAPIClient::PageSizeInfo`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'complexity')
        self.complexity = attributes[:'complexity']
      else
        self.complexity = 'none'
      end

      if attributes.key?(:'issue_name')
        self.issue_name = attributes[:'issue_name']
      end

      if attributes.key?(:'issue_type')
        self.issue_type = attributes[:'issue_type']
      else
        self.issue_type = 'unknown'
      end

      if attributes.key?(:'pages_over_1mb')
        self.pages_over_1mb = attributes[:'pages_over_1mb']
      else
        self.pages_over_1mb = nil
      end

      if attributes.key?(:'total_pages')
        self.total_pages = attributes[:'total_pages']
      else
        self.total_pages = nil
      end

      if attributes.key?(:'_links')
        self._links = attributes[:'_links']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @complexity.nil?
        invalid_properties.push('invalid value for "complexity", complexity cannot be nil.')
      end

      if @issue_type.nil?
        invalid_properties.push('invalid value for "issue_type", issue_type cannot be nil.')
      end

      if @pages_over_1mb.nil?
        invalid_properties.push('invalid value for "pages_over_1mb", pages_over_1mb cannot be nil.')
      end

      if @total_pages.nil?
        invalid_properties.push('invalid value for "total_pages", total_pages cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @complexity.nil?
      complexity_validator = EnumAttributeValidator.new('String', ["none", "low", "medium", "high", "extreme"])
      return false unless complexity_validator.valid?(@complexity)
      return false if @issue_type.nil?
      issue_type_validator = EnumAttributeValidator.new('String', ["unknown", "technical", "content", "ux", "mobile", "keyword"])
      return false unless issue_type_validator.valid?(@issue_type)
      return false if @pages_over_1mb.nil?
      return false if @total_pages.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] complexity Object to be assigned
    def complexity=(complexity)
      validator = EnumAttributeValidator.new('String', ["none", "low", "medium", "high", "extreme"])
      unless validator.valid?(complexity)
        fail ArgumentError, "invalid value for \"complexity\", must be one of #{validator.allowable_values}."
      end
      @complexity = complexity
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] issue_type Object to be assigned
    def issue_type=(issue_type)
      validator = EnumAttributeValidator.new('String', ["unknown", "technical", "content", "ux", "mobile", "keyword"])
      unless validator.valid?(issue_type)
        fail ArgumentError, "invalid value for \"issue_type\", must be one of #{validator.allowable_values}."
      end
      @issue_type = issue_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          complexity == o.complexity &&
          issue_name == o.issue_name &&
          issue_type == o.issue_type &&
          pages_over_1mb == o.pages_over_1mb &&
          total_pages == o.total_pages &&
          _links == o._links
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [complexity, issue_name, issue_type, pages_over_1mb, total_pages, _links].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = SiteimproveAPIClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
